openapi: 3.0.3
info:
  title: Order and Cart Service API
  version: 1.0.0
  description: API для управления заказами и корзиной

servers:
  - url: http://localhost:8082

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Order:
      type: object
      properties:
        id:
          type: string
          format: uuid
        customer_id:
          type: string
          format: uuid
        status:
          type: string
        total_price:
          type: number
          format: float
        created_at:
          type: string
          format: date-time

    Good:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        price:
          type: number
          format: float

    CreateOrderRequest:
      type: object
      properties:
        status:
          type: string
        total_price:
          type: number
          format: float

    AddRemoveProductRequest:
      type: object
      properties:
        product:
          type: string

    OrderResponse:
      type: object
      properties:
        order:
          $ref: '#/components/schemas/Order'
        goods:
          type: array
          items:
            $ref: '#/components/schemas/Good'

paths:

  /order/create:
    post:
      summary: Создать новый заказ
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateOrderRequest'
      responses:
        '201':
          description: Заказ успешно создан, возвращает ID заказа
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid

  /order/get/{id}:
    get:
      summary: Получить информацию о заказе по ID
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Информация о заказе и связанных товарах
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderResponse'
        '404':
          description: Заказ не найден или недоступен для пользователя

  /order/info?status={status}&limit={limit}&offset={offset} :
    get :
      summary : Получить список заказов с фильтрацией и пагинацией 
      security :
        - BearerAuth : []
      parameters :
        - name : status 
          in : query 
          required : false 
          schema : 
            type : string 
        - name : limit 
          in : query 
          required : false 
          schema : 
            type : integer 
            default : 0 
        - name : offset 
          in : query 
          required : false 
          schema : 
            type : integer 
            default : 0 
      responses :
        '200' :
           description : Список заказов пользователя 
           content :
             application/json :
               schema :
                 type : array 
                 items :
                   $ref : '#/components/schemas/Order' 

  /cart/add :
    post :
      summary : Добавить товар в корзину пользователя  
      security :
        - BearerAuth : []
      requestBody :
        required : true 
        content :
           application/json :
             schema :
               $ref : '#/components/schemas/AddRemoveProductRequest'  
      responses :
         '200' :
           description : Товар успешно добавлен в корзину  

  /cart/remove :
    post :
      summary : Удалить товар из корзины пользователя  
      security :
        - BearerAuth : []
      requestBody :
        required : true 
        content :
           application/json :
             schema :
               $ref : '#/components/schemas/AddRemoveProductRequest'  
      responses :
         '200' :
           description : Товар успешно удален из корзины  

  /order/create-from-cart :
    post :
      summary : Создать заказ на основе содержимого корзины  
      security :
        - BearerAuth : []
      responses :
         '201' :
           description : Заказ создан, возвращает ID заказа  
           content :
             application/json :
               schema :
                 type : object 
                 properties :
                   order_id :
                     type : string 
                     format : uuid  