// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package transport

import (
	"buyers-service/internal/interfaces"
	"buyers-service/internal/models/request"
	"buyers-service/internal/models/response"
	"context"
	"github.com/google/uuid"
)

type BuyersServiceRegister func(ctx context.Context, email string, password string, buyer request.BuyerCreate) (userID uuid.UUID, err error)
type BuyersServiceLogin func(ctx context.Context, email string, password string) (token string, err error)
type BuyersServiceGetBuyer func(ctx context.Context, id uuid.UUID) (res response.BuyerInfo, err error)
type BuyersServiceDeleteUser func(ctx context.Context, id uuid.UUID) (err error)

type MiddlewareBuyersService func(next interfaces.BuyersService) interfaces.BuyersService

type MiddlewareBuyersServiceRegister func(next BuyersServiceRegister) BuyersServiceRegister
type MiddlewareBuyersServiceLogin func(next BuyersServiceLogin) BuyersServiceLogin
type MiddlewareBuyersServiceGetBuyer func(next BuyersServiceGetBuyer) BuyersServiceGetBuyer
type MiddlewareBuyersServiceDeleteUser func(next BuyersServiceDeleteUser) BuyersServiceDeleteUser
