// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package transport

import (
	"buyers-service/internal/models/request"
	"buyers-service/internal/models/response"
	"github.com/google/uuid"
)

type requestBuyersServiceRegister struct {
	Email    string              `json:"email,omitempty"`
	Password string              `json:"password,omitempty"`
	Buyer    request.BuyerCreate `json:"buyer,omitempty"`
}

type responseBuyersServiceRegister struct {
	UserID uuid.UUID `json:"userID,omitempty"`
}

type requestBuyersServiceLogin struct {
	Email    string `json:"email,omitempty"`
	Password string `json:"password,omitempty"`
}

type responseBuyersServiceLogin struct {
	Token string `json:"token,omitempty"`
}

type requestBuyersServiceGetBuyer struct {
	Id uuid.UUID `json:"id,omitempty"`
}

type responseBuyersServiceGetBuyer struct {
	Res response.BuyerInfo `json:"res,omitempty"`
}

type requestBuyersServiceDeleteUser struct {
	Id uuid.UUID `json:"id,omitempty"`
}

// Formal exchange type, please do not delete.
type responseBuyersServiceDeleteUser struct{}
