version: '3.8'

services:
  server:
    platform: linux/amd64
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file:
      - configs/buyersservice_docker.env
    ports:
      - '127.0.0.1:80:8080'
      - '127.0.0.1:9090:9090'
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: buyer_info
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data: