version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: market
      POSTGRES_MAX_CONNECTIONS: 50
      PGUSER: postgres
    ports:
      - "7000:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "market"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s  
  market:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
      - "9090:9090"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - configs/docker.env